### ISSUE TITLE
Deploy pipeline fails

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-hdr10plus#47]
I noticed that the latest version was not deployed to GitHub pages. Seems that something is failing in the publishing pipeline.

**Comment by cconcolato** [comment]
The pipeline says:
```
  [INFO] Build bikeshed document "index.bs" (common)…
    $ bikeshed --die-on=fatal spec "index.bs" "index.bs.built.html" 
      Traceback (most recent call last):
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/bin/bikeshed", line 8, in <module>
          sys.exit(main())
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/lib/python3.8/site-packages/bikeshed/cli.py", line 423, in main
          handleSpec(options, extras)
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/lib/python3.8/site-packages/bikeshed/cli.py", line 478, in handleSpec
          doc.preprocess()
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/lib/python3.8/site-packages/bikeshed/Spec.py", line 145, in preprocess
          self.processDocument()
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/lib/python3.8/site-packages/bikeshed/Spec.py", line 264, in processDocument
          boilerplate.addIndexSection(self)
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/lib/python3.8/site-packages/bikeshed/boilerplate.py", line 304, in addIndexSection
          addIndexOfExternallyDefinedTerms(doc, container)
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/lib/python3.8/site-packages/bikeshed/boilerplate.py", line 570, in addIndexOfExternallyDefinedTerms
          dfnpanels.addExternalDfnPanel(link, ref, doc)
        File "/home/runner/work/_actions/w3c/spec-prod/v2/python_modules/lib/python3.8/site-packages/bikeshed/dfnpanels.py", line 99, in addExternalDfnPanel
          for link in doc.cachedLinksFromHref[ref.url]:
      KeyError: '#biblio-av1'
    Failed
  Error: Process completed with exit code 1.
```

**Comment by podborski** [comment]
Something is wrong with the "#biblio-av1"? Not so sure what the problem is here. Also on my end it seems to compile without errors. Do you see the same error message if you do it locally on your end?

**Comment by cconcolato** [comment]
No I don't have any errors. I even did a `bikeshed update` to see if it was a version issue, but it doesn't fail.

**Comment by cconcolato** [comment]
After re-installing bikeshed:
```
pip3 install bikeshed 
bikeshed update
```
I can reproduce the failure locally.

**Comment by cconcolato** [comment]
I found a workaround and opened an issue with bikeshed.
